name: 5-Minutters Beredskapssjekk

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

# Tvinger GitHub til å kjøre alt på den nye, sikre Node 24-motoren:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  sjekk-alle:
    runs-on: ubuntu-latest

    steps:
    - name: Henter kode
      uses: actions/checkout@v4

    - name: Setter opp Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installerer pakker
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Kjører Svipper, HRS og NSSR
      env:
        SLACK_BREAKING: ${{ secrets.SLACK_BREAKING }}
        SLACK_TRAFIKK: ${{ secrets.SLACK_TRAFIKK }}
      run: |
        python svipper_varsel.py
        python hrs_script.py
        python nssr_script.py
